import type { FreexsterState } from "./types";

export const demoState: FreexsterState = {
  activeSurface: "inbox",
  activeThreadId: "thread-simplex-onboarding",
  activeChannelId: "channel-freexster-design",
  nativeStatus: {
    runtime: "web",
    simplexRunner: "mock-connected",
    registry: "mock",
  },
  simplexRunner: {
    runtime: "web",
    host: "127.0.0.1",
    port: 5225,
    webSocketUrl: "ws://127.0.0.1:5225",
    state: "desktop-required",
    configured: false,
    canConnect: false,
    binaryPath: null,
    lastError: "SimpleX runner status is available in the Freexster desktop app.",
    securityBoundary: "SimpleX CLI WebSocket is unauthenticated; Freexster only probes 127.0.0.1.",
  },
  inboxThreads: [
    {
      id: "thread-simplex-onboarding",
      subject: "SimpleX onboarding notes",
      correspondent: "Ari",
      preview: "Desktop-first runner integration keeps the private inbox local.",
      unread: true,
      labels: ["SimpleX", "v1"],
      updatedAt: "2026-06-27T08:30:00Z",
      route: "simplex-local",
      trust: [
        { label: "SimpleX contact", state: "pending", detail: "Contact proof ready for verification." },
        { label: "Registry identity", state: "verified", detail: "Principal linked to Freexster registry." },
      ],
    },
    {
      id: "thread-agent-model",
      subject: "Agent permissions model",
      correspondent: "Maya",
      preview: "Agents stay visible in the architecture but execution is not in v1.",
      unread: true,
      labels: ["Agents", "Permissions"],
      updatedAt: "2026-06-27T07:10:00Z",
      route: "simplex-local",
      trust: [{ label: "Canister proof", state: "verified", detail: "Policy hash is anchored in the registry." }],
    },
    {
      id: "thread-public-replies",
      subject: "Private replies from topic channels",
      correspondent: "Noor",
      preview: "A public channel post can open a private SimpleX reply path.",
      unread: false,
      labels: ["Channels"],
      updatedAt: "2026-06-26T23:45:00Z",
      route: "simplex-local",
      trust: [{ label: "Route", state: "verified", detail: "Private reply route stays off-chain." }],
    },
  ],
  channels: [
    {
      id: "channel-freexster-design",
      slug: "freexster-design",
      title: "Freexster Design",
      charter: "Product design, UX, and trust model decisions for the working-title Freexster project.",
      steward: "General Magick Industries",
      status: "approved",
      costStatus: "healthy",
      trust: [
        { label: "Channel canister", state: "pending", detail: "Mock canister proof until registry canister exists." },
        { label: "Founder steward", state: "verified", detail: "Launch steward is explicitly listed." },
      ],
      posts: [
        {
          id: "post-inbox-first",
          author: "Mark",
          title: "Inbox-first is the product spine",
          body: "Freexster starts as a personal communications home, then grows outward into public identity, agents, and wallet trust.",
          replyCount: 8,
          repostCount: 1,
          createdAt: "2026-06-27T09:00:00Z",
          certified: true,
        },
      ],
    },
    {
      id: "channel-simplex-onboarding",
      slug: "simplex-onboarding",
      title: "SimpleX Onboarding",
      charter: "Helping people understand the downloaded app, local runner, and private inbox boundaries.",
      steward: "Freexster launch team",
      status: "approved",
      costStatus: "healthy",
      trust: [{ label: "Posting policy", state: "verified", detail: "Curated channel with public request path." }],
      posts: [],
    },
    {
      id: "channel-icp-trust-network",
      slug: "icp-trust-network",
      title: "ICP Trust Network",
      charter: "Registry, certified public reads, confidential subnet posture, and vetKeys design.",
      steward: "Freexster launch team",
      status: "approved",
      costStatus: "watch",
      trust: [{ label: "Cycle monitor", state: "pending", detail: "Cost controls required before permissionless channels." }],
      posts: [],
    },
    {
      id: "channel-autonomous-agents",
      slug: "autonomous-agents",
      title: "Autonomous Agents",
      charter: "Independent agent accounts, agent wallets, and public provenance.",
      steward: "Requested",
      status: "requested",
      costStatus: "restricted",
      trust: [{ label: "Request", state: "pending", detail: "Channel creation is curated in v1." }],
      posts: [],
    },
  ],
  channelRequests: [
    {
      id: "request-agent-comms",
      requestedSlug: "agent-comms",
      requestedBy: "Mark",
      rationale: "Design future robot-to-robot and AI-agent communications without making it a v1 dependency.",
      status: "under-review",
    },
  ],
  agents: [
    {
      id: "agent-design-placeholder",
      name: "Design Placeholder",
      provider: "design-placeholder",
      enabled: false,
      permissions: ["Read selected thread after user approval", "Draft response after user approval"],
      auditSummary: "No agent execution in v1; permissions model is visible for design review.",
    },
  ],
};
